### ISSUE TITLE
Benchmarking work checklist

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#1575]
Now that https://github.com/rails-api/active_model_serializers/pull/1393#issuecomment-194111133 is merged, there's some follow-up work to do and consider:

- [ ] Docs
  - [ ] when and how devs should use
  - [ ] command line options to `bin/bench` <br> `bin/bench --help`<br>
`Usage: bin/bench [options]`<br>
`    -r, --repeat-count [NUM]         Run benchmarks [NUM] times taking the best result`<br>
`    -p <PATTERN1,PATTERN2,PATTERN3>, Benchmark name pattern`<br>
`        --pattern`<br>
`    -e <var1=val1,var2=val2,var3=vale>,`<br>
`        --env                        ENV variables to pass in`
  - [ ] ENV vars that can be passed to `bin/bench`
    - [ ] SUMMARIZE, CACHE_ON, FAIL_ASSERTION, DEBUG, BENCH_STRESS, ENABLE_ACTIVE_RECORD
  - [ ] adding another runner (just model off of exiting)
- [ ] consolidate dummy app with [isolated app](https://github.com/rails-api/active_model_serializers/blob/7ab39bed858f49e1cc1a5350c878e43e67898643/test/support/isolated_unit.rb) and [test helper app](https://github.com/rails-api/active_model_serializers/blob/7ab39bed858f49e1cc1a5350c878e43e67898643/test/support/rails_app.rb)
- [ ] consider renaming dummy to `benchmark`
- [ ] consider removing from this PR:
  - [ ] active record
  - [ ] bench stress
  - [ ] bin/serve_dummy
  - [ ] summary
  - [ ] logger options
- [ ] review for dead code, options, comments, etc.
- [ ] add Rails version to output https://github.com/rails-api/active_model_serializers/pull/1393#discussion_r52940978
- [ ] *after merge* followup with @ianks in https://github.com/rails-api/active_model_serializers/pull/1511
- [ ] decide what goes in a followup pr
  - [ ] running in CI?
  - [ ] running in [ruby-bench-suite](https://github.com/ruby-bench/ruby-bench-suite/) or our own?
  - [ ] running against actioncontroller::base and actioncontroller::API
  - [ ] [regression runner (across revisions)](https://github.com/rails-api/active_model_serializers/blob/d0845248ced0297341ed4d5cf4a31f2bcfa026fd/bin/bench_regression)
  - [ ] [FakeIPS](https://github.com/rails-api/active_model_serializers/blob/d0845248ced0297341ed4d5cf4a31f2bcfa026fd/test/dummy/benchmarking_support.rb#L17-L152) for running without needing to vendor benchmark-ips
  - [ ] [derailed benchmarks](https://github.com/rails-api/active_model_serializers/blob/d0845248ced0297341ed4d5cf4a31f2bcfa026fd/tasklib/perf.rake) [gemfile](https://github.com/rails-api/active_model_serializers/blob/d0845248ced0297341ed4d5cf4a31f2bcfa026fd/Gemfile#L39-L45)
  - [ ] [rack-mini-profiler](https://github.com/rails-api/active_model_serializers/blob/d0845248ced0297341ed4d5cf4a31f2bcfa026fd/test/dummy/app.rb#L57-L63)
